### ISSUE TITLE
Make FAP separate library

### ISSUE THREAD

**Issue by kant2002** [N00byEdge/Neohuman#18]
FAP is very useful library. I personally use it as second option for my bot, and during the testing of the Sparcraft. SteamHammer also use your library. Both I and Jay Scott create small tweaks to library to integrate to the bot. Changes are trivial, but nonetheless it is mundane tasks to update FAP if you do any improvements. I think the only change which is needed is replace constructor `FAPUnit(EnemyData)` with operator which will reside in the different file. For my bot and SteamHammer similar file should be created, and it would be task of bot author to create such integration. But core logic of FAP in that case remain the same. Also I know that SteamHammer do small constants calibration to the FAP, so that also could be exposed as parameters. I could submit PR if you agree on the spirit of this request.

**Comment by N00byEdge** [comment]
Yes I will separate FAP from the bot. The bot using it will provide its own `makeFAPUnit(T const &unit)`. On the parameters, I'll see with the community what they have changed and would like to have the ability to do.

**Comment by kant2002** [comment]
@N00byEdge you could use this link to compare what changes Jay done: https://github.com/kant2002/steamhammer/blame/master/Steamhammer/Source/FAP.cpp

**Comment by N00byEdge** [comment]
Finally! https://github.com/N00byEdge/FAP
